import type { Locale } from '@/config/locales';
import type { AttendeeExperienceContent } from '../types/attendee-experience';

/*
 * Development fixture for the attendee journey. Real content arrives
 * from the Registration Engine once participant identity lands.
 */
export const DEMO_ATTENDEE_SLUG = 'demo';

const demoAttendee: Record<Locale, AttendeeExperienceContent> = {
  he: {
    slug: 'demo',
    speakers: [
      { id: 's1', name: 'פרופ׳ דנה ברק', role: 'חוקרת בינה מלאכותית', photoUrl: 'https://i.pravatar.cc/640?img=32' },
      { id: 's2', name: 'אלון שדה', role: 'משרד הדיגיטל', photoUrl: 'https://i.pravatar.cc/640?img=12' },
      { id: 's3', name: 'רות אליאב', role: 'עיריית חיפה', photoUrl: 'https://i.pravatar.cc/640?img=47' },
      { id: 's4', name: 'נעם פרידמן', role: 'רשות החדשנות', photoUrl: 'https://i.pravatar.cc/640?img=68' },
    ],
    brandName: 'נטעים',
    navigation: [
      { label: 'האירוע שלי', href: '#my-event' },
      { label: 'היום שלי', href: '#my-day' },
      { label: 'אנשים', href: '#networking' },
      { label: 'הכניסה שלי', href: '#entrance' },
    ],
    welcome: {
      greeting: 'שלום, דנה',
      heading: 'הכול מוכן לקראתך',
      countdownTarget: '2026-09-01T06:00:00Z',
      countdownLabel: 'ימים לאירוע',
      eventDateLabel: '1 בספטמבר 2026',
      venueLine: 'מרכז הכנסים הלאומי, ירושלים',
      primaryCta: { label: 'ליום שלי', href: '#my-day' },
      secondaryCta: { label: 'לכניסה שלי', href: '#entrance' },
    },
    myEvent: {
      label: 'האירוע שלי',
      heading: 'כנס הדגמה 2026',
      summary: 'יום אחד של מפגשים, סדנאות ושיחות פתוחות עם אנשי המגזר הציבורי. ההרשמה שלך מאושרת — נשאר רק להגיע.',
      statusLabel: 'סטטוס הרשמה',
      statusValue: 'מאושרת',
      image: { url: 'https://picsum.photos/seed/hason-lounge-dusk/2400/1200', alt: 'מרכז הכנסים' },
      updates: [
        {
          id: 'update-1',
          dateLabel: 'עדכון אחרון',
          title: 'נפתחה סדנה נוספת',
          text: 'בעקבות הביקוש נפתחה קבוצה שנייה לסדנה המעשית בשעה 10:30.',
        },
        {
          id: 'update-2',
          title: 'הגעה מוקדמת',
          text: 'שערי המתחם ייפתחו ב-08:30. מומלץ להגיע מוקדם לקפה של פתיחה.',
        },
      ],
    },
    myDay: {
      label: 'היום שלי',
      heading: 'המסלול האישי שלך',
      intro: 'המושבים ששמרת, ההפסקות, והמלצה אחת שחשבנו שתאהבי.',
      savedLabel: 'שמור עבורך',
      moments: [
        {
          id: 'moment-1',
          startTime: '09:00',
          endTime: '10:00',
          title: 'מושב פתיחה',
          description: 'התכנסות, דברי פתיחה והצבת הכיוון ליום.',
          room: 'אולם מרכזי',
          saved: true,
        },
        {
          id: 'moment-2',
          startTime: '10:30',
          sessionType: 'workshop',
          endTime: '12:00',
          title: 'סדנה מעשית',
          description: 'הקבוצה שלך: קבוצה ב׳.',
          room: 'חדר 2',
          saved: true,
        },
        {
          id: 'moment-3',
          startTime: '12:00',
          endTime: '13:00',
          title: 'הפסקת צהריים',
          kind: 'break',
          room: 'המרפסת',
        },
        {
          id: 'moment-4',
          startTime: '13:00',
          endTime: '14:30',
          title: 'שיחות בגובה העיניים',
          description: 'מנהיגות המגזר בשיח פתוח עם הקהל.',
          room: 'אולם מרכזי',
          note: 'מומלץ עבורך',
        },
      ],
    },
    networking: {
      label: 'אנשים שכדאי להכיר',
      heading: 'מי עוד יהיה שם',
      intro: 'ארבעה אנשים שנראה לנו ששווה לך לפגוש — לפי המושבים ששמרת.',
      people: [
        {
          id: 'person-1',
          name: 'נועה ברק',
          role: 'רשות החדשנות',
          photoUrl: '/demo/portrait-2.jpg',
          photoAlt: 'נועה ברק',
          reason: 'נרשמה לאותה סדנה מעשית — עובדת על אתגר דומה לשלך.',
        },
        {
          id: 'person-2',
          name: 'אלון שדה',
          role: 'משרד הדיגיטל',
          photoUrl: '/demo/portrait-4.jpg',
          photoAlt: 'אלון שדה',
          reason: 'הוביל פרויקט שירות דומה בשנה שעברה, ישמח לשתף.',
        },
        {
          id: 'person-3',
          name: 'רות אליאב',
          role: 'עיריית חיפה',
          photoUrl: '/demo/portrait-1.jpg',
          photoAlt: 'רות אליאב',
          reason: 'תחומי עניין משותפים: שירות דיגיטלי ונגישות.',
        },
        {
          id: 'person-4',
          name: 'דוד מזרחי',
          role: 'ביטוח לאומי',
          photoUrl: '/demo/portrait-3.jpg',
          photoAlt: 'דוד מזרחי',
          reason: 'יושב בפאנל שסימנת — אפשר לתפוס אותו אחריו.',
        },
      ],
    },
    entrance: {
      label: 'הכניסה שלי',
      heading: 'הכול מוכן בכניסה',
      text: 'הציגי את הקוד בכניסה למתחם. הוא שמור גם במכשיר וזמין ללא אינטרנט.',
      qrValue: 'נטעים-DEMO-2026-D-COHEN-0001',
      qrCaption: 'קוד הכניסה האישי שלך',
      statusLabel: 'סטטוס כרטיס',
      statusValue: 'מאושר לכניסה',
      details: [
        { id: 'arrival', label: 'שעת הגעה מומלצת', value: '08:30–09:00' },
        { id: 'gate', label: 'כניסה', value: 'שער ראשי, קומת הכניסה' },
        { id: 'help', label: 'עזרה במקום', value: 'עמדת המידע ליד שער הכניסה' },
        { id: 'emergency', label: 'חירום', value: 'צוות האבטחה בכל אולם' },
      ],
      offlineNote: 'העמוד נשמר לצפייה גם ללא חיבור לרשת.',
    },
    after: {
      label: 'אחרי האירוע',
      heading: 'מה שנשאר איתך',
      text: 'החומרים, התמונות והתעודה שלך יחכו כאן אחרי האירוע — נעדכן אותך כשהם מוכנים.',
      resources: [
        {
          id: 'certificate',
          kindLabel: 'תעודה',
          title: 'אישור השתתפות',
          pendingNote: 'זמין לאחר האירוע',
        },
        {
          id: 'slides',
          kindLabel: 'מצגות',
          title: 'חומרי המושבים ששמרת',
          pendingNote: 'יעלו תוך שבוע',
        },
        {
          id: 'photos',
          kindLabel: 'תמונות',
          title: 'אלבום האירוע',
          pendingNote: 'יעלה תוך שבוע',
        },
      ],
      nextEventLine: 'האירוע הבא של הארגון יוכרז כאן.',
    },
  },
  en: {
    slug: 'demo',
    speakers: [
      { id: 's1', name: 'Prof. Dana Barak', role: 'AI Researcher', photoUrl: 'https://i.pravatar.cc/640?img=32' },
      { id: 's2', name: 'Alon Sade', role: 'Digital Ministry', photoUrl: 'https://i.pravatar.cc/640?img=12' },
      { id: 's3', name: 'Ruth Eliav', role: 'Haifa Municipality', photoUrl: 'https://i.pravatar.cc/640?img=47' },
      { id: 's4', name: 'Noam Friedman', role: 'Innovation Authority', photoUrl: 'https://i.pravatar.cc/640?img=68' },
    ],
    brandName: 'נטעים',
    navigation: [
      { label: 'My event', href: '#my-event' },
      { label: 'My day', href: '#my-day' },
      { label: 'People', href: '#networking' },
      { label: 'My entrance', href: '#entrance' },
    ],
    welcome: {
      greeting: 'Hello, Dana',
      heading: 'Everything is ready for you',
      countdownTarget: '2026-09-01T06:00:00Z',
      countdownLabel: 'days to the event',
      eventDateLabel: 'September 1, 2026',
      venueLine: 'The National Convention Center, Jerusalem',
      primaryCta: { label: 'To my day', href: '#my-day' },
      secondaryCta: { label: 'To my entrance', href: '#entrance' },
    },
    myEvent: {
      label: 'My event',
      heading: 'Demo Conference 2026',
      summary: 'One day of sessions, workshops and open conversations with public-sector peers. Your registration is confirmed — all that remains is to arrive.',
      statusLabel: 'Registration status',
      statusValue: 'Confirmed',
      image: { url: 'https://picsum.photos/seed/hason-lounge-dusk/2400/1200', alt: 'The convention center' },
      updates: [
        {
          id: 'update-1',
          dateLabel: 'Latest update',
          title: 'An additional workshop opened',
          text: 'Due to demand, a second group opened for the 10:30 hands-on workshop.',
        },
        {
          id: 'update-2',
          title: 'Early arrival',
          text: 'Gates open at 08:30. Come early for the opening coffee.',
        },
      ],
    },
    myDay: {
      label: 'My day',
      heading: 'Your personal route',
      intro: 'The sessions you saved, the breaks, and one recommendation we thought you would like.',
      savedLabel: 'Saved for you',
      moments: [
        {
          id: 'moment-1',
          startTime: '09:00',
          endTime: '10:00',
          title: 'Opening Session',
          description: 'Gathering, opening words and setting the direction for the day.',
          room: 'Main Hall',
          saved: true,
        },
        {
          id: 'moment-2',
          startTime: '10:30',
          sessionType: 'workshop',
          endTime: '12:00',
          title: 'Hands-on Workshop',
          description: 'Your group: Group B.',
          room: 'Room 2',
          saved: true,
        },
        {
          id: 'moment-3',
          startTime: '12:00',
          endTime: '13:00',
          title: 'Lunch break',
          kind: 'break',
          room: 'The Terrace',
        },
        {
          id: 'moment-4',
          startTime: '13:00',
          endTime: '14:30',
          title: 'Eye-level conversations',
          description: 'Sector leadership in open conversation with the audience.',
          room: 'Main Hall',
          note: 'Recommended for you',
        },
      ],
    },
    networking: {
      label: 'People worth meeting',
      heading: 'Who else will be there',
      intro: 'Four people we think you should meet — based on the sessions you saved.',
      people: [
        {
          id: 'person-1',
          name: 'Noa Barak',
          role: 'Innovation Authority',
          photoUrl: '/demo/portrait-2.jpg',
          photoAlt: 'Noa Barak',
          reason: 'Registered for the same workshop — working on a challenge like yours.',
        },
        {
          id: 'person-2',
          name: 'Alon Sadeh',
          role: 'Ministry of Digital Affairs',
          photoUrl: '/demo/portrait-4.jpg',
          photoAlt: 'Alon Sadeh',
          reason: 'Led a similar service project last year and is happy to share.',
        },
        {
          id: 'person-3',
          name: 'Ruth Eliav',
          role: 'Haifa Municipality',
          photoUrl: '/demo/portrait-1.jpg',
          photoAlt: 'Ruth Eliav',
          reason: 'Shared interests: digital service and accessibility.',
        },
        {
          id: 'person-4',
          name: 'David Mizrahi',
          role: 'National Insurance',
          photoUrl: '/demo/portrait-3.jpg',
          photoAlt: 'David Mizrahi',
          reason: 'On the panel you marked — catch him right after.',
        },
      ],
    },
    entrance: {
      label: 'My entrance',
      heading: 'Everything is ready at the door',
      text: 'Show this code at the venue entrance. It is stored on your device and works without internet.',
      qrValue: 'נטעים-DEMO-2026-D-COHEN-0001',
      qrCaption: 'Your personal entrance code',
      statusLabel: 'Ticket status',
      statusValue: 'Approved for entry',
      details: [
        { id: 'arrival', label: 'Recommended arrival', value: '08:30–09:00' },
        { id: 'gate', label: 'Entrance', value: 'Main gate, ground floor' },
        { id: 'help', label: 'Help on site', value: 'Information desk by the gate' },
        { id: 'emergency', label: 'Emergency', value: 'Security staff in every hall' },
      ],
      offlineNote: 'This page is saved for offline viewing.',
    },
    after: {
      label: 'After the event',
      heading: 'What stays with you',
      text: 'Your materials, photos and certificate will wait here after the event — we will let you know when they are ready.',
      resources: [
        {
          id: 'certificate',
          kindLabel: 'Certificate',
          title: 'Attendance certificate',
          pendingNote: 'Available after the event',
        },
        {
          id: 'slides',
          kindLabel: 'Presentations',
          title: 'Materials from your saved sessions',
          pendingNote: 'Uploaded within a week',
        },
        {
          id: 'photos',
          kindLabel: 'Photos',
          title: 'The event album',
          pendingNote: 'Uploaded within a week',
        },
      ],
      nextEventLine: 'The organization’s next event will be announced here.',
    },
  },
};

export const getDemoAttendee = (locale: Locale): AttendeeExperienceContent =>
  demoAttendee[locale];
