import type { Locale } from '@/config/locales';

/*
 * The Lounge's voice: every word the personal space speaks, in both
 * languages. A guest is addressed, never administered.
 */
export const LOUNGE_UI = {
  myExperience: { he: 'המסע שלי', en: 'My Journey' },
  schedule: { he: 'לוח הזמנים', en: 'Schedule' },
  networking: { he: 'נטוורקינג', en: 'Networking' },
  messages: { he: 'הודעות', en: 'Messages' },
  speakers: { he: 'דוברים', en: 'Speakers' },
  mapVenue: { he: 'מפה ומקום', en: 'Map & Venue' },
  resources: { he: 'חומרים', en: 'Resources' },
  helpCenter: { he: 'מרכז עזרה', en: 'Help Center' },
  logOut: { he: 'התנתקות', en: 'Log out' },
  myConferences: { he: 'הכנסים שלי', en: 'My conferences' },
  notRegisteredNote: {
    he: 'אינך רשומ/ה לאף כנס עדיין. אלו הכנסים הפתוחים להצטרפות:',
    en: 'You are not registered to any conference yet. These are open to join:',
  },
  noOpenConferences: {
    he: 'אין כרגע כנסים פתוחים. ברגע שכנס יעלה לאוויר — הוא יופיע כאן.',
    en: 'No conferences are open right now. The moment one goes live, it appears here.',
  },
  joinConference: { he: 'להצטרף', en: 'Join' },
  openLounge: { he: 'כניסה ללאונג׳', en: 'Open lounge' },
  registeredActivities: { he: 'ההרשמות שלי', en: 'Your registrations' },
  viewFullProgram: { he: 'לתוכנית המלאה', en: 'View full program' },
  onWaitlist: { he: 'רשימת המתנה', en: 'Waitlist' },
  activityDetailsHint: { he: 'לפרטים וביטול', en: 'Details & cancel' },
  noTicketNote: {
    he: 'עדיין אין כרטיס — הוא ייוולד עם ההרשמה הראשונה שלך.',
    en: 'No ticket yet — it is born with your first registration.',
  },
  noTicketCta: { he: 'לכנסים הפתוחים', en: 'See open conferences' },
  emptySchedule: {
    he: 'הלו״ז שלך יתמלא ברגע שתירשמו לכנס.',
    en: 'Your schedule fills the moment you join a conference.',
  },
  emptyNetworking: {
    he: 'אנשים להכיר יופיעו כאן בתוך הכנס.',
    en: 'People to meet appear here inside a conference.',
  },
  daysUnit: { he: 'ימים', en: 'days' },
  hoursUnit: { he: 'שעות', en: 'hours' },
  minutesUnit: { he: 'דקות', en: 'minutes' },
  welcomeBackBig: { he: 'נרגשים לראות אותך שוב', en: 'Wonderful to see you again' },
  heroSubline: {
    he: 'העתיד מתחיל כאן — והמסע שלך ממשיך.',
    en: 'The future starts here — and your journey continues.',
  },
  continueJourney: { he: 'המשך להכנת הכנס שלך', en: 'Continue preparing your conference' },
  nextActionTitle: { he: 'הפעולה הבאה שלך', en: 'Your next step' },
  actionChooseWorkshops: { he: 'בחר סדנאות', en: 'Choose workshops' },
  actionChooseWorkshopsSub: {
    he: 'ההרשמה לסדנאות בעיצומה — אל תחמיץ את המקומות הטובים.',
    en: 'Workshop registration is open — the good seats go first.',
  },
  actionNetworking: { he: 'הנטוורקינג פתוח', en: 'Networking is open' },
  actionNetworkingSub: {
    he: 'אנשים מחכים להכיר אותך. שלח בקשת היכרות ראשונה.',
    en: 'People are waiting to meet you. Send your first request.',
  },
  actionJoin: { he: 'הצטרפו לכנס', en: 'Join a conference' },
  actionJoinSub: {
    he: 'המסע מתחיל בכנס הראשון שלך.',
    en: 'The journey begins with your first conference.',
  },
  actionReady: { he: 'הכול מוכן', en: 'You are all set' },
  actionReadySub: {
    he: 'הלו״ז שלך סגור והכרטיס מחכה. נתראה שם.',
    en: 'Your schedule is set and your ticket is waiting. See you there.',
  },
  chosenOf: { he: 'נבחרו', en: 'Chosen' },
  outOf: { he: 'מתוך', en: 'of' },
  journeyChooseSessions: { he: 'בחירת סדנאות', en: 'Choose sessions' },
  journeyDay: { he: 'יום הכנס', en: 'Conference day' },
  journeyDone: { he: 'הושלם', en: 'Completed' },
  leadingSpeakers: { he: 'דוברים מובילים', en: 'Leading speakers' },
  seeAllSpeakers: { he: 'צפה בכל הדוברים', en: 'See all speakers' },
  waitingForYou: { he: 'ממתינים לראות אותך', en: 'Waiting to see you' },
  needHelp: { he: 'זקוק לעזרה?', en: 'Need a hand?' },
  helpSub: {
    he: 'צוות שירות המשתתפים זמין עבורך.',
    en: 'The participant care team is here for you.',
  },
  contactSupport: { he: 'פנייה לתמיכה', en: 'Contact support' },
  myTicketNav: { he: 'הכרטיס שלי', en: 'My ticket' },
  fullScreen: { he: 'הצג מסך מלא', en: 'Full screen' },
  requestsTitle: { he: 'בקשות היכרות', en: 'Connection requests' },
  meetingsTitle: { he: 'פגישות', en: 'Meetings' },
  feedTitle: { he: 'עדכונים מהכנס', en: 'Conference updates' },
  accept: { he: 'אישור', en: 'Accept' },
  decline: { he: 'דחייה', en: 'Decline' },
  confirm: { he: 'אישור', en: 'Confirm' },
  cancel: { he: 'ביטול', en: 'Cancel' },
  noMessages: {
    he: 'שקט כרגע. בקשות, פגישות ועדכונים יופיעו כאן.',
    en: 'Quiet for now. Requests, meetings and updates appear here.',
  },
  wantsToConnect: { he: 'רוצה להתחבר איתך', en: 'wants to connect with you' },
  meetingWith: { he: 'פגישה עם', en: 'Meeting with' },
  journeyAccount: { he: 'חשבון', en: 'Account' },
  journeyTicket: { he: 'כרטיס', en: 'Ticket' },
  journeySchedule: { he: 'לו״ז', en: 'Schedule' },
  journeyNetworking: { he: 'נטוורקינג', en: 'Networking' },
  journeyConference: { he: 'הכנס', en: 'Conference' },
  afterThanks: {
    he: 'תודה שהייתם איתנו. היה מרגש.',
    en: 'Thank you for being with us. It was moving.',
  },
  afterRecordings: {
    he: 'הקלטות וחומרים יופיעו כאן ברגע שיעלו.',
    en: 'Recordings and materials appear here the moment they are up.',
  },
  latestUpdate: { he: 'עדכון אחרון', en: 'Latest update' },
  speakersTitle: { he: 'הדוברים שלנו', en: 'Our speakers' },
  noSpeakers: {
    he: 'הדוברים יוכרזו בקרוב.',
    en: 'Speakers will be announced soon.',
  },
  venueTitle: { he: 'מפה ומקום', en: 'Map & venue' },
  openInMaps: { he: 'פתיחה במפות', en: 'Open in maps' },
  emptyUpdates: {
    he: 'עדכונים מהכנס שלך יופיעו כאן.',
    en: 'Updates from your conference appear here.',
  },
  home: { he: 'בית', en: 'Home' },
  agenda: { he: 'לו"ז', en: 'Agenda' },
  profile: { he: 'פרופיל', en: 'Profile' },
  welcomeBack: { he: 'טוב לראות אותך שוב,', en: 'Welcome back,' },
  daysToGo: { he: 'ימים לפתיחה', en: 'DAYS TO GO' },
  cantWait: {
    he: 'אנחנו כבר מחכים לראות אותך.',
    en: 'We can’t wait to see you there.',
  },
  editProfile: { he: 'עריכת פרופיל', en: 'Edit Profile' },
  myTicket: { he: 'הכרטיס שלי', en: 'My Ticket' },
  participant: { he: 'משתתף/ת', en: 'Participant' },
  addToWallet: { he: 'הוספה ל-Wallet', en: 'Add to Wallet' },
  mySchedule: { he: 'הלו"ז שלי', en: 'My Schedule' },
  viewFullAgenda: { he: 'ללו"ז המלא', en: 'View full agenda' },
  connections: { he: 'קשרים', en: 'Connections' },
  pending: { he: 'ממתינים', en: 'Pending' },
  seeAll: { he: 'לכולם', en: 'See all' },
  peopleToMeet: {
    he: 'אנשים ששווה להכיר',
    en: 'People you may want to meet',
  },
  findMorePeople: { he: 'לעוד אנשים', en: 'Find more people' },
  updates: { he: 'עדכונים', en: 'Updates' },
  allUpdates: { he: 'כל העדכונים', en: 'All updates' },
  recommended: { he: 'מומלץ בשבילך', en: 'Recommended for you' },
  myPass: { he: 'הכרטיס שלי', en: 'My Pass' },
  passCaption: {
    he: 'הציגו בכניסה — הסורק עושה את השאר.',
    en: 'Show this at the entrance — the scanner does the rest.',
  },
  close: { he: 'סגירה', en: 'Close' },
  connect: { he: 'התחברות', en: 'Connect' },
  statusLabel: { he: 'מצב הרשמה', en: 'Registration' },
  profileTitle: { he: 'הפרופיל שלי', en: 'My Profile' },
  profileSub: {
    he: 'הפרטים שאיתם נקבל את פניך — ומה שאחרים יראו אם בחרת בנטוורקינג.',
    en: 'The details we greet you with — and what others see if you opted in.',
  },
  fieldName: { he: 'שם מלא', en: 'Full name' },
  fieldPhone: { he: 'נייד', en: 'Mobile' },
  fieldOrganization: { he: 'ארגון / מוסד', en: 'Organization' },
  fieldRole: { he: 'תפקיד', en: 'Role' },
  fieldDietary: { he: 'העדפות תזונה', en: 'Dietary preferences' },
  fieldAccessibility: { he: 'צורכי נגישות', en: 'Accessibility needs' },
  saveProfile: { he: 'שמירה', en: 'Save' },
  profileSaved: { he: 'נשמר. נתראה בכנס.', en: 'Saved. See you there.' },
  backToLounge: { he: 'חזרה לחוויה שלי', en: 'Back to My Experience' },
  checkInOpen: { he: 'הצ׳ק-אין פתוח', en: 'Check-in is open' },
  showPassAtGate: {
    he: 'הציגו את הכרטיס בכניסה — נתראה בפנים.',
    en: 'Show your pass at the entrance — see you inside.',
  },
  nextForYou: { he: 'הבא בתור בשבילך', en: 'Next for you' },
} satisfies Record<string, Record<Locale, string>>;
