import type { Locale } from '@/config/locales';

/*
 * Labels for the Studio's content editors — the platform's own panel,
 * in both languages. Payload vocabulary never leaks here.
 */
export const EDITOR_MESSAGES: Record<string, Record<Locale, string>> = {
  homepageTitle: { he: 'דף הבית', en: 'Homepage' },
  homepageIntro: {
    he: 'כל מה שמבקר רואה בכניסה לפלטפורמה — נערך כאן. שדה ריק חוזר לנוסח הקולנועי המובנה.',
    en: 'Everything a visitor sees at the entrance — edited here. An empty field falls back to the built-in cinematic copy.',
  },
  openingTitle: { he: 'הפתיחה', en: 'Opening' },
  openingIntro: {
    he: 'העולם של הכנס: הפוסטר, האווירה והסיפור שמבקר פוגש לפני כל מידע מעשי.',
    en: 'The conference world: the poster, atmosphere and story a visitor meets before any practical information.',
  },
  sectionHero: { he: 'פתיח', en: 'Hero' },
  sectionEvents: { he: 'מדור הכנסים', en: 'Events section' },
  sectionStory: { he: 'הסיפור', en: 'The story' },
  sectionMoments: { he: 'רגעים', en: 'Moments' },
  sectionClosing: { he: 'סגירה', en: 'Closing' },
  sectionPortal: { he: 'פוסטר ואווירה', en: 'Poster & atmosphere' },
  sectionArrival: { he: 'קבלת פנים', en: 'Arrival' },
  sectionQuote: { he: 'ציטוט', en: 'Quote' },
  sectionVenue: { he: 'המקום', en: 'Venue' },
  heroTitleMain: { he: 'כותרת — שורה ראשונה', en: 'Title — first line' },
  heroTitleAccent: { he: 'כותרת — שורת ההדגשה', en: 'Title — accent line' },
  heroSubtitle: { he: 'משפט תומך', en: 'Supporting sentence' },
  heroImage: { he: 'תמונת רקע', en: 'Backdrop image' },
  eventsTitle: { he: 'כותרת המדור', en: 'Section title' },
  eventsSubtitle: { he: 'תת־כותרת', en: 'Subtitle' },
  storyEyebrow: { he: 'שורת פתיחה קטנה', en: 'Eyebrow line' },
  storyTitle: { he: 'כותרת', en: 'Title' },
  storyParagraph: { he: 'פסקה', en: 'Paragraph' },
  storyImage: { he: 'תמונה', en: 'Image' },
  momentsTitle: { he: 'כותרת', en: 'Title' },
  closingTitle: { he: 'שורת הסיום', en: 'Closing line' },
  closingSubtitle: { he: 'משפט משלים', en: 'Second line' },
  closingCta: { he: 'טקסט הכפתור', en: 'Button text' },
  teaser: { he: 'משפט רגשי (טיזר)', en: 'Emotional sentence (teaser)' },
  location: { he: 'מיקום', en: 'Location' },
  featured: { he: 'הכנס המוביל של דף הבית', en: 'Featured on the homepage' },
  atmosphere: { he: 'אווירה', en: 'Atmosphere' },
  poster: { he: 'פוסטר (3:4)', en: 'Poster (3:4)' },
  heroBackdrop: { he: 'תמונת פתיח רחבה', en: 'Wide hero backdrop' },
  arrivalEyebrow: { he: 'שורת פתיחה קטנה', en: 'Eyebrow line' },
  quoteText: { he: 'הציטוט', en: 'The quote' },
  quoteAttribution: { he: 'שם הדובר/ת', en: 'Attribution' },
  quoteRole: { he: 'תפקיד / הקשר', en: 'Role / context' },
  quoteStatValue: { he: 'מספר (אופציונלי)', en: 'Number (optional)' },
  quoteStatLabel: { he: 'תיאור המספר', en: 'Number caption' },
  venueName: { he: 'שם המקום', en: 'Venue name' },
  venueNarrative: { he: 'על המקום — משפט או שניים', en: 'About the place — a sentence or two' },
  closingLine: { he: 'שורת הסיום', en: 'Closing line' },
  noImage: { he: 'ללא תמונה (ברירת מחדל)', en: 'No image (default)' },
  save: { he: 'שמירה', en: 'Save' },
  saved: { he: 'נשמר', en: 'Saved' },
  contentLanguage: { he: 'שפת התוכן', en: 'Content language' },
  notFound: { he: 'האירוע לא נמצא.', en: 'Event not found.' },
  teamTitle: { he: 'צוות', en: 'Team' },
  teamIntro: {
    he: 'האנשים שמנהלים את הפלטפורמה: הוספה, שמות ותפקידים. הרשאות נאכפות לפי תפקיד.',
    en: 'The people who run the platform: add members, names and roles. Permissions follow the role.',
  },
  memberName: { he: 'שם', en: 'Name' },
  memberEmail: { he: 'אימייל', en: 'Email' },
  memberPassword: { he: 'סיסמה ראשונית', en: 'Initial password' },
  memberRole: { he: 'תפקיד', en: 'Role' },
  addMember: { he: 'הוספת חבר/ת צוות', en: 'Add team member' },
  membersList: { he: 'חברי הצוות', en: 'Members' },
  rename: { he: 'עדכון שם', en: 'Update name' },
};

export const ROLE_LABELS: Record<string, Record<Locale, string>> = {
  platformOwner: { he: 'בעלי הפלטפורמה', en: 'Platform owner' },
  orgAdmin: { he: 'מנהל/ת הארגון', en: 'Organization admin' },
  eventManager: { he: 'מנהל/ת אירועים', en: 'Event manager' },
  contentEditor: { he: 'עורך/ת תוכן', en: 'Content editor' },
  registrationManager: { he: 'מנהל/ת הרשמה', en: 'Registration manager' },
  volunteerManager: { he: 'מנהל/ת מתנדבים', en: 'Volunteer manager' },
  reviewer: { he: 'מבקר/ת', en: 'Reviewer' },
  readOnly: { he: 'צפייה בלבד', en: 'Read only' },
};

export const ATMOSPHERE_LABELS: Record<string, Record<Locale, string>> = {
  bronze: { he: 'ברונזה ממלכתית', en: 'Civic bronze' },
  innovation: { he: 'חדשנות — כחול קריר', en: 'Innovation — cool blue' },
  daylight: { he: 'אור יום רך', en: 'Soft daylight' },
  morning: { he: 'שמש של בוקר', en: 'Morning sun' },
  nature: { he: 'ירוק טבעי', en: 'Natural green' },
  stage: { he: 'תאורת במה', en: 'Stage light' },
};
