/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    organizations: Organization;
    users: User;
    media: Media;
    events: Event;
    experiences: Experience;
    scenes: Scene;
    speakers: Speaker;
    sponsors: Sponsor;
    participants: Participant;
    'account-grants': AccountGrant;
    registrations: Registration;
    'registration-settings': RegistrationSetting;
    'participant-sessions': ParticipantSession;
    notifications: Notification;
    rooms: Room;
    sessions: Session;
    'session-registrations': SessionRegistration;
    'networking-profiles': NetworkingProfile;
    'networking-connections': NetworkingConnection;
    'networking-chat-messages': NetworkingChatMessage;
    'networking-meetings': NetworkingMeeting;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    scenes: ScenesSelect<false> | ScenesSelect<true>;
    speakers: SpeakersSelect<false> | SpeakersSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    participants: ParticipantsSelect<false> | ParticipantsSelect<true>;
    'account-grants': AccountGrantsSelect<false> | AccountGrantsSelect<true>;
    registrations: RegistrationsSelect<false> | RegistrationsSelect<true>;
    'registration-settings': RegistrationSettingsSelect<false> | RegistrationSettingsSelect<true>;
    'participant-sessions': ParticipantSessionsSelect<false> | ParticipantSessionsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    rooms: RoomsSelect<false> | RoomsSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    'session-registrations': SessionRegistrationsSelect<false> | SessionRegistrationsSelect<true>;
    'networking-profiles': NetworkingProfilesSelect<false> | NetworkingProfilesSelect<true>;
    'networking-connections': NetworkingConnectionsSelect<false> | NetworkingConnectionsSelect<true>;
    'networking-chat-messages': NetworkingChatMessagesSelect<false> | NetworkingChatMessagesSelect<true>;
    'networking-meetings': NetworkingMeetingsSelect<false> | NetworkingMeetingsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('he' | 'en') | ('he' | 'en')[];
  globals: {
    'platform-settings': PlatformSetting;
    'opening-page': OpeningPage;
    site: Site;
  };
  globalsSelect: {
    'platform-settings': PlatformSettingsSelect<false> | PlatformSettingsSelect<true>;
    'opening-page': OpeningPageSelect<false> | OpeningPageSelect<true>;
    site: SiteSelect<false> | SiteSelect<true>;
  };
  locale: 'he' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  grants?:
    | {
        role:
          | 'platformOwner'
          | 'orgAdmin'
          | 'eventManager'
          | 'contentEditor'
          | 'registrationManager'
          | 'volunteerManager'
          | 'reviewer'
          | 'readOnly';
        organization?: (number | null) | Organization;
        event?: (number | null) | Event;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Scene order and visibility — directed from the Studio
   */
  composition?:
    | {
        scene: string;
        hidden?: boolean | null;
        variant?: string | null;
        density?: string | null;
        emphasis?: string | null;
        id?: string | null;
      }[]
    | null;
  organization: number | Organization;
  title: string;
  slug: string;
  defaultLocale: 'he' | 'en';
  experience?: (number | null) | Experience;
  startsAt?: string | null;
  endsAt?: string | null;
  location?: string | null;
  teaser?: string | null;
  poster?: (number | null) | Media;
  heroImage?: (number | null) | Media;
  featured?: boolean | null;
  /**
   * Conference opening experience content
   */
  opening?: {
    arrivalEyebrow?: string | null;
    story?: {
      eyebrow?: string | null;
      title?: string | null;
      paragraph?: string | null;
      image?: (number | null) | Media;
    };
    quote?: {
      text?: string | null;
      attribution?: string | null;
      role?: string | null;
      image?: (number | null) | Media;
      statValue?: string | null;
      statLabel?: string | null;
    };
    moments?:
      | {
          image?: (number | null) | Media;
          caption?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Chosen voices on stage: an existing platform account, or a manual name and photo
     */
    speakers?:
      | {
          account?: (number | null) | Participant;
          name?: string | null;
          role?: string | null;
          photo?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Per-day themes for the program journey (Day 1, 2, 3…): one row per conference day, in order
     */
    programDays?:
      | {
          theme?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    venue?: {
      name?: string | null;
      narrative?: string | null;
      accessibilityInfo?: string | null;
      emergencyInfo?: string | null;
      image?: (number | null) | Media;
      facts?:
        | {
            label?: string | null;
            description?: string | null;
            icon?: ('accessibility' | 'parking' | 'transit' | 'hotel' | 'leaf' | 'coffee') | null;
            id?: string | null;
          }[]
        | null;
    };
    closing?: {
      line?: string | null;
      image?: (number | null) | Media;
    };
  };
  atmosphere?: ('bronze' | 'innovation' | 'daylight' | 'morning' | 'nature' | 'stage') | null;
  phase:
    | 'draft'
    | 'planning'
    | 'registrationOpen'
    | 'registrationClosed'
    | 'preparation'
    | 'live'
    | 'completed'
    | 'archived';
  capabilities?:
    | (
        | 'registration'
        | 'payments'
        | 'networking'
        | 'certificates'
        | 'checkIn'
        | 'notifications'
        | 'waitlist'
        | 'liveUpdates'
        | 'surveys'
        | 'resources'
        | 'streaming'
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  organization: number | Organization;
  title: string;
  scenes?: (number | Scene)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scenes".
 */
export interface Scene {
  id: number;
  organization: number | Organization;
  title: string;
  type: string;
  content?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  organization: number | Organization;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants".
 */
export interface Participant {
  id: number;
  organization: number | Organization;
  name: string;
  email: string;
  /**
   * Derived credential material. Never displayed or edited.
   */
  passwordHash?: string | null;
  /**
   * Second-factor secret. Never displayed or edited.
   */
  totpSecret?: string | null;
  totpEnabledAt?: string | null;
  phone?: string | null;
  /**
   * Which channels open to approved connections. Private by default.
   */
  contactPrefs?: {
    whatsapp?: boolean | null;
    phone?: boolean | null;
    email?: boolean | null;
    meetings?: boolean | null;
  };
  accessibilityNeeds?: string | null;
  dietary?: string | null;
  orgName?: string | null;
  roleTitle?: string | null;
  /**
   * Comma-separated interests shown on the profile card
   */
  interests?: string | null;
  photo?: (number | null) | Media;
  /**
   * A blocked participant cannot enter the personal lounge
   */
  blocked?: boolean | null;
  anonymizedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers".
 */
export interface Speaker {
  id: number;
  organization: number | Organization;
  event?: (number | null) | Event;
  /**
   * Link an existing נטעים account. Its profile fills the details below; leave any field empty to inherit, or fill it to override for this conference.
   */
  account?: (number | null) | Participant;
  /**
   * External name, or an override for a linked account.
   */
  name?: string | null;
  jobTitle?: string | null;
  company?: string | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  /**
   * Public links (LinkedIn, X, personal site…).
   */
  socialLinks?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Legacy title field — prefer Job Title above.
   */
  role?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  organization: number | Organization;
  event: number | Event;
  name: string;
  tier: 'platinum' | 'gold' | 'silver' | 'partner';
  logo?: (number | null) | Media;
  website?: string | null;
  description?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-grants".
 */
export interface AccountGrant {
  id: number;
  organization: number | Organization;
  account: number | Participant;
  role: 'owner' | 'producer' | 'editor' | 'door' | 'viewer';
  /**
   * Scope the grant to one conference. Empty = platform-wide.
   */
  event?: (number | null) | Event;
  grantedBy?: (number | null) | Participant;
  grantedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations".
 */
export interface Registration {
  id: number;
  organization: number | Organization;
  participant: number | Participant;
  event: number | Event;
  status: 'pending' | 'confirmed' | 'waitlisted' | 'cancelled' | 'declined' | 'attended' | 'expired' | 'noShow';
  answers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  waitlistPosition?: number | null;
  offerExpiresAt?: string | null;
  cancelledReason?: string | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registration-settings".
 */
export interface RegistrationSetting {
  id: number;
  organization: number | Organization;
  event: number | Event;
  mode: 'open' | 'approval' | 'invitation';
  capacity?: number | null;
  opensAt?: string | null;
  closesAt?: string | null;
  waitlistEnabled?: boolean | null;
  confirmationMessage?: string | null;
  collectPhone?: boolean | null;
  collectAccessibility?: boolean | null;
  collectDietary?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participant-sessions".
 */
export interface ParticipantSession {
  id: number;
  organization: number | Organization;
  participant: number | Participant;
  tokenHash: string;
  purpose: 'sign-in';
  expiresAt: string;
  usedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  organization: number | Organization;
  participant?: (number | null) | Participant;
  event?: (number | null) | Event;
  type: string;
  channel: 'email';
  status: 'queued' | 'sent' | 'failed';
  locale?: string | null;
  subject?: string | null;
  body?: string | null;
  sentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms".
 */
export interface Room {
  id: number;
  organization: number | Organization;
  event: number | Event;
  name: string;
  capacity?: number | null;
  location?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  organization: number | Organization;
  event: number | Event;
  title: string;
  description?: string | null;
  sessionType: 'talk' | 'workshop' | 'keynote' | 'break' | 'tour';
  /**
   * One or more speakers leading this activity
   */
  speakers?: (number | Speaker)[] | null;
  room?: (number | null) | Room;
  track?: string | null;
  startsAt?: string | null;
  endsAt?: string | null;
  capacity?: number | null;
  waitlistEnabled?: boolean | null;
  /**
   * Show this session in the Featured Sessions on the landing
   */
  featured?: boolean | null;
  /**
   * Thumbnail shown on the Featured Sessions cards
   */
  image?: (number | null) | Media;
  language?: string | null;
  equipment?: string | null;
  subtitle?: string | null;
  floor?: string | null;
  registrationOpensAt?: string | null;
  registrationClosesAt?: string | null;
  allowCancellation?: boolean | null;
  cancellationDeadline?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "session-registrations".
 */
export interface SessionRegistration {
  id: number;
  organization: number | Organization;
  participant: number | Participant;
  session: number | Session;
  event: number | Event;
  status: 'pending' | 'confirmed' | 'waitlisted' | 'cancelled' | 'declined' | 'attended' | 'expired' | 'noShow';
  waitlistPosition?: number | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "networking-profiles".
 */
export interface NetworkingProfile {
  id: number;
  organization: number | Organization;
  event: number | Event;
  participant: number | Participant;
  headline?: string | null;
  bio?: string | null;
  interests?: string | null;
  links?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  visible?: boolean | null;
  availableForMeetings?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "networking-connections".
 */
export interface NetworkingConnection {
  id: number;
  organization: number | Organization;
  event: number | Event;
  requester: number | Participant;
  addressee: number | Participant;
  status: 'pending' | 'accepted' | 'declined' | 'muted' | 'removed';
  mutedBy?: string | null;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "networking-chat-messages".
 */
export interface NetworkingChatMessage {
  id: number;
  organization: number | Organization;
  connection: number | NetworkingConnection;
  sender: number | Participant;
  body: string;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "networking-meetings".
 */
export interface NetworkingMeeting {
  id: number;
  organization: number | Organization;
  event: number | Event;
  host: number | Participant;
  guest: number | Participant;
  startsAt: string;
  endsAt: string;
  location?: string | null;
  status: 'proposed' | 'confirmed' | 'cancelled';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'scenes';
        value: number | Scene;
      } | null)
    | ({
        relationTo: 'speakers';
        value: number | Speaker;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'participants';
        value: number | Participant;
      } | null)
    | ({
        relationTo: 'account-grants';
        value: number | AccountGrant;
      } | null)
    | ({
        relationTo: 'registrations';
        value: number | Registration;
      } | null)
    | ({
        relationTo: 'registration-settings';
        value: number | RegistrationSetting;
      } | null)
    | ({
        relationTo: 'participant-sessions';
        value: number | ParticipantSession;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'rooms';
        value: number | Room;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'session-registrations';
        value: number | SessionRegistration;
      } | null)
    | ({
        relationTo: 'networking-profiles';
        value: number | NetworkingProfile;
      } | null)
    | ({
        relationTo: 'networking-connections';
        value: number | NetworkingConnection;
      } | null)
    | ({
        relationTo: 'networking-chat-messages';
        value: number | NetworkingChatMessage;
      } | null)
    | ({
        relationTo: 'networking-meetings';
        value: number | NetworkingMeeting;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  grants?:
    | T
    | {
        role?: T;
        organization?: T;
        event?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  organization?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  composition?:
    | T
    | {
        scene?: T;
        hidden?: T;
        variant?: T;
        density?: T;
        emphasis?: T;
        id?: T;
      };
  organization?: T;
  title?: T;
  slug?: T;
  defaultLocale?: T;
  experience?: T;
  startsAt?: T;
  endsAt?: T;
  location?: T;
  teaser?: T;
  poster?: T;
  heroImage?: T;
  featured?: T;
  opening?:
    | T
    | {
        arrivalEyebrow?: T;
        story?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              paragraph?: T;
              image?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              attribution?: T;
              role?: T;
              image?: T;
              statValue?: T;
              statLabel?: T;
            };
        moments?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
            };
        speakers?:
          | T
          | {
              account?: T;
              name?: T;
              role?: T;
              photo?: T;
              id?: T;
            };
        programDays?:
          | T
          | {
              theme?: T;
              description?: T;
              id?: T;
            };
        venue?:
          | T
          | {
              name?: T;
              narrative?: T;
              accessibilityInfo?: T;
              emergencyInfo?: T;
              image?: T;
              facts?:
                | T
                | {
                    label?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
            };
        closing?:
          | T
          | {
              line?: T;
              image?: T;
            };
      };
  atmosphere?: T;
  phase?: T;
  capabilities?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  organization?: T;
  title?: T;
  scenes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scenes_select".
 */
export interface ScenesSelect<T extends boolean = true> {
  organization?: T;
  title?: T;
  type?: T;
  content?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers_select".
 */
export interface SpeakersSelect<T extends boolean = true> {
  organization?: T;
  event?: T;
  account?: T;
  name?: T;
  jobTitle?: T;
  company?: T;
  bio?: T;
  photo?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  organization?: T;
  event?: T;
  name?: T;
  tier?: T;
  logo?: T;
  website?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants_select".
 */
export interface ParticipantsSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  email?: T;
  passwordHash?: T;
  totpSecret?: T;
  totpEnabledAt?: T;
  phone?: T;
  contactPrefs?:
    | T
    | {
        whatsapp?: T;
        phone?: T;
        email?: T;
        meetings?: T;
      };
  accessibilityNeeds?: T;
  dietary?: T;
  orgName?: T;
  roleTitle?: T;
  interests?: T;
  photo?: T;
  blocked?: T;
  anonymizedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-grants_select".
 */
export interface AccountGrantsSelect<T extends boolean = true> {
  organization?: T;
  account?: T;
  role?: T;
  event?: T;
  grantedBy?: T;
  grantedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations_select".
 */
export interface RegistrationsSelect<T extends boolean = true> {
  organization?: T;
  participant?: T;
  event?: T;
  status?: T;
  answers?: T;
  waitlistPosition?: T;
  offerExpiresAt?: T;
  cancelledReason?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registration-settings_select".
 */
export interface RegistrationSettingsSelect<T extends boolean = true> {
  organization?: T;
  event?: T;
  mode?: T;
  capacity?: T;
  opensAt?: T;
  closesAt?: T;
  waitlistEnabled?: T;
  confirmationMessage?: T;
  collectPhone?: T;
  collectAccessibility?: T;
  collectDietary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participant-sessions_select".
 */
export interface ParticipantSessionsSelect<T extends boolean = true> {
  organization?: T;
  participant?: T;
  tokenHash?: T;
  purpose?: T;
  expiresAt?: T;
  usedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  organization?: T;
  participant?: T;
  event?: T;
  type?: T;
  channel?: T;
  status?: T;
  locale?: T;
  subject?: T;
  body?: T;
  sentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  organization?: T;
  event?: T;
  name?: T;
  capacity?: T;
  location?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  organization?: T;
  event?: T;
  title?: T;
  description?: T;
  sessionType?: T;
  speakers?: T;
  room?: T;
  track?: T;
  startsAt?: T;
  endsAt?: T;
  capacity?: T;
  waitlistEnabled?: T;
  featured?: T;
  image?: T;
  language?: T;
  equipment?: T;
  subtitle?: T;
  floor?: T;
  registrationOpensAt?: T;
  registrationClosesAt?: T;
  allowCancellation?: T;
  cancellationDeadline?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "session-registrations_select".
 */
export interface SessionRegistrationsSelect<T extends boolean = true> {
  organization?: T;
  participant?: T;
  session?: T;
  event?: T;
  status?: T;
  waitlistPosition?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "networking-profiles_select".
 */
export interface NetworkingProfilesSelect<T extends boolean = true> {
  organization?: T;
  event?: T;
  participant?: T;
  headline?: T;
  bio?: T;
  interests?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  visible?: T;
  availableForMeetings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "networking-connections_select".
 */
export interface NetworkingConnectionsSelect<T extends boolean = true> {
  organization?: T;
  event?: T;
  requester?: T;
  addressee?: T;
  status?: T;
  mutedBy?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "networking-chat-messages_select".
 */
export interface NetworkingChatMessagesSelect<T extends boolean = true> {
  organization?: T;
  connection?: T;
  sender?: T;
  body?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "networking-meetings_select".
 */
export interface NetworkingMeetingsSelect<T extends boolean = true> {
  organization?: T;
  event?: T;
  host?: T;
  guest?: T;
  startsAt?: T;
  endsAt?: T;
  location?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-settings".
 */
export interface PlatformSetting {
  id: number;
  platformName: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opening-page".
 */
export interface OpeningPage {
  id: number;
  /**
   * Scene order and visibility — directed from the Studio
   */
  composition?:
    | {
        scene: string;
        hidden?: boolean | null;
        id?: string | null;
      }[]
    | null;
  hero?: {
    titleMain?: string | null;
    titleAccent?: string | null;
    subtitle?: string | null;
    image?: (number | null) | Media;
  };
  events?: {
    title?: string | null;
    subtitle?: string | null;
  };
  story?: {
    eyebrow?: string | null;
    title?: string | null;
    paragraph?: string | null;
    image?: (number | null) | Media;
  };
  moments?: {
    title?: string | null;
    items?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  closing?: {
    title?: string | null;
    subtitle?: string | null;
    cta?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  /**
   * The published conference shown as the public website (its landing, program, speakers and information).
   */
  activeConference?: (number | null) | Event;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-settings_select".
 */
export interface PlatformSettingsSelect<T extends boolean = true> {
  platformName?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opening-page_select".
 */
export interface OpeningPageSelect<T extends boolean = true> {
  composition?:
    | T
    | {
        scene?: T;
        hidden?: T;
        id?: T;
      };
  hero?:
    | T
    | {
        titleMain?: T;
        titleAccent?: T;
        subtitle?: T;
        image?: T;
      };
  events?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  story?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        paragraph?: T;
        image?: T;
      };
  moments?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  closing?:
    | T
    | {
        title?: T;
        subtitle?: T;
        cta?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  activeConference?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}