import { CollectionCards as CollectionCards_f9c02e79a4aed9a3924487c0cd4cafb1 } from '@payloadcms/next/rsc';

/*
 * Generated by `payload generate:importmap`. Regenerate whenever custom
 * admin components are added.
 */
export const importMap = {
  '@payloadcms/next/rsc#CollectionCards':
    CollectionCards_f9c02e79a4aed9a3924487c0cd4cafb1,
};
